const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(
	process.env.MONGODB_URI || "mongodb://localhost/cooolprojects"
);

const projectSeed = [
	{
		client: "K-Swiss\nMethod & Madness",
		mainPageActive: true,
		title: "Hideout",
		year: "2022",
		credits:
			"Director: coool\nExecutive Producer: Casey Lock\nProducer: Brendan Brown\nProd. Company: Method and Madness\n\nDP: Kevin Horn\n1st AC: Javier Castillo & Carlos Cabrera-Mayol\nSteadicam Op: Kevin Veselka\n\nGaffer: Stephen Wester\nKey Grip: William Westgaard\nGrip: Brandon Hinsley\n\n1st AD: Phil Evans\nPA: Alex Leeds\n\nProduction Designer: Mitch Ransdell\nEditor: Max Mooney\nColorist: Kevin Horn\nOriginal Music, Sound Design and Mix: Ethan Houser\n\nThank you to:\nJorie and Mike Landfear\nChinatown Square Association\nThe Grove\nAtlas Lighting\n\nThief #1: Kenyon Ellsworth\nGuard #1: Nic Gohl\nThief #2: Jimmy Sisto\nThief #3: Ryan Nolen\nGuard #2: Buddy Heeley",
		preview:
			"https://drive.google.com/file/d/1JM4qSy8XMWQpy8noCtIMUDJSMuF_vi4q/view",
		fullVideo: "https://vimeo.com/589106246",
		stillImg:
			"https://drive.google.com/file/d/1-4NifBOt4qw0eDExMM44Y5_Ddb1oYcsQ/view",
		notes: "",
	},
	{
		client: "Kum & Go\nBrand Opus",
		mainPageActive: false,
		title: "Sad Food, Fresh Food",
		year: "2022",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Walker\nMajestic Casual",
		mainPageActive: false,
		title: "Majestic Sessions",
		year: "2022",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Portraits of Men Crying",
		mainPageActive: true,
		title: "Portraits of Men Crying",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Ratboys\nTopshelf Records",
		mainPageActive: false,
		title: "Happy Birthday Ratboy",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Disq\nSaddle Creek Records",
		mainPageActive: false,
		title: "Gentle",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Sam Evian\nFat Possum Records",
		mainPageActive: true,
		title: "Time to Melt",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Tasha\nFather Daughter Records",
		mainPageActive: false,
		title: "Perfect Wife",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Lainey Strange\nLGM Records",
		mainPageActive: false,
		title: "Cowgirl Angels",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Pet Symmetry\nTriple Crown Records",
		mainPageActive: true,
		title: "2021: A Personal Space Odyssey",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},

	{
		client: "Into It. Over It.\nTriple Crown Records",
		mainPageActive: true,
		title: "Dressing Down",
		year: "2021",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Gagosian\nLittle Dot Studios",
		mainPageActive: true,
		title: "Gagosian Premieres: Gregory Crewdson",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Ratboys\nTopshelf Records",
		mainPageActive: false,
		title: "I Go Out at Night",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Hala\nCinematic Records",
		mainPageActive: true,
		title: "Emotional R&B",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Hala\nCinematic Records",
		mainPageActive: true,
		title: "Somehow",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Slow Pulp\nWinspear Records",
		mainPageActive: true,
		title: "At It Again",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Deeper\nFire Talk Records",
		mainPageActive: true,
		title: "The Knife",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Into It. Over It.\nTriple Crown Records",
		mainPageActive: false,
		title: "We Prefer Indoors",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Tenci\nKeeled Scales Records",
		mainPageActive: true,
		title: "No Wings",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Tenci\nKeeled Scales Records",
		mainPageActive: false,
		title: "Forgot My Horses Name",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Tenci\nKeeled Scales Records",
		mainPageActive: false,
		title: "Serpent",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Disq\nSaddle Creek Records",
		mainPageActive: true,
		title: "Daily Routine",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},

	{
		client: "Disq\nSaddle Creek Records",
		mainPageActive: true,
		title: "Loneliness",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Fat Night\nAcrophase Records",
		mainPageActive: false,
		title: "Live For Each Other",
		year: "2020",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Ratboys\nTopshelf Records",
		mainPageActive: true,
		title: "Alien With A Sleepmask On",
		year: "2019",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Kim Tee",
		mainPageActive: false,
		title: "Too Deep",
		year: "2019",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Katie Dey\nRun For Cover Records",
		mainPageActive: true,
		title: "Dissolving",
		year: "2019",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Spencer Radcliffe\nRun For Cover Records",
		mainPageActive: true,
		title: "Here Comes the Snow",
		year: "2019",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Fat Night\nAcrophase Records",
		mainPageActive: false,
		title: "Sweet Nothings",
		year: "2019",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Nike x Off-White\nPiff MPLS",
		mainPageActive: false,
		title: "",
		year: "2018",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Muerte's Death",
		mainPageActive: true,
		title: "Muerte's Death",
		year: "2018",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Urban Outfitters\nDizzy Fae",
		mainPageActive: true,
		title: "New Sounds x Dizzy Fae",
		year: "2018",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "Space Gators",
		mainPageActive: false,
		title: "Is it Right? Is it Wrong?",
		year: "2018",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "La Croix",
		mainPageActive: false,
		title: "Crying",
		year: "2019",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	{
		client: "REI",
		mainPageActive: false,
		title: "Two of Us",
		year: "2018",
		credits: "",
		preview: "",
		fullVideo: "",
		stillImg: "",
		notes: "",
	},
	// {
	// 	client: "",
	//  mainPageActive: false,
	// 	title: "",
	// 	year: "",
	// 	credits: "",
	// 	preview: "",
	// 	fullVideo: "",
	// 	stillImg: "",
	// 	notes: "",
	// },
];
